### ISSUE TITLE
代码尺寸过大，无法生成hex文件

### ISSUE THREAD

**Issue by HychoX** [MRobot-Origin/GS_Hbed#1]
在Keil上对stc12c5a60s2编译时，出现以下报错
```
* RESTRICTED VERSION WITH 0800H BYTE CODE SIZE LIMIT; USED: 0B26H BYTE (139%) *
******************************************************************************
Program Size: data=116.1 xdata=0 const=176 code=6109
*** ERROR L257: UNKNOWN
Target not created.
Build Time Elapsed:  00:00:01
```
请问该如何解决，或是应该更换主控芯片

**Comment by MRobot-Origin** [comment]
你需要在Keil中导入STC系列芯片的头文件，具体方法可以百度，很简单。芯片型号选对应该就能正常编译了。


在2021年12月20日 ***@***.***> 写道：

在Keil上对stc12c5a60s2编译时，出现以下报错

* RESTRICTED VERSION WITH 0800H BYTE CODE SIZE LIMIT; USED: 0B26H BYTE (139%) *

******************************************************************************

Program Size: data=116.1 xdata=0 const=176 code=6109

*** ERROR L257: UNKNOWN

Target not created.

Build Time Elapsed:  00:00:01



请问该如何解决，或是应该更换主控芯片

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HychoX** [comment]
解决了，同时发现我的keil注册码过期了，更新以后即可编译生成hex，谢谢您
